// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models.Entitites
{
    public partial class Car
    {
        public Car()
        {
            Trip = new HashSet<Trip>();
        }

        public int CarId { get; set; }
        public string LicensePlate { get; set; }
        public int SysBrandId { get; set; }
        public int SysModelId { get; set; }
        public int SysTypeId { get; set; }

        public virtual ICollection<Trip> Trip { get; set; }
    }
}