// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models.Entitites
{
    public partial class City
    {
        public int CityId { get; set; }
        public string Name { get; set; }
        public int? CountyId { get; set; }
        public int? CountryId { get; set; }

        public virtual County County { get; set; }
    }
}