// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models
{
    public partial class Country
    {
        public int CountryId { get; set; }
        public string Name { get; set; }
        public int? LanguageId { get; set; }
    }
}