// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models
{
    public partial class Driver
    {
        public int DriverId { get; set; }
        public int UserId { get; set; }
        public int LicenseId { get; set; }
        public int RatingId { get; set; }
        public int CarId { get; set; }
        public DateTime CreationDate { get; set; }
        public bool? IsActive { get; set; }

        public virtual Car Car { get; set; }
        public virtual License License { get; set; }
        public virtual User User { get; set; }
    }
}