// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models
{
    public partial class GeoLocation
    {
        public GeoLocation()
        {
            Location = new HashSet<Location>();
        }

        public int GeoLocationId { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }

        public virtual ICollection<Location> Location { get; set; }
    }
}