// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models
{
    public partial class Location
    {
        public int LocationId { get; set; }
        public int GeoLocationId { get; set; }
        public bool? IsLandMark { get; set; }
        public string LandMarkName { get; set; }
        public int? RelatedLocationId { get; set; }
        public int? CityId { get; set; }
        public int? CountyId { get; set; }

        public virtual GeoLocation GeoLocation { get; set; }
    }
}