// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models
{
    public partial class Payment
    {
        public Payment()
        {
            Trip = new HashSet<Trip>();
        }

        public int PaymentId { get; set; }
        public DateTime CreationDate { get; set; }
        public decimal? BaseAmount { get; set; }
        public decimal? SurgeAmount { get; set; }
        public decimal? TotalAmount { get; set; }
        public string CardAccountNo { get; set; }
        public int? TransactionId { get; set; }

        public virtual ICollection<Trip> Trip { get; set; }
    }
}