// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models
{
    public partial class SysRating
    {
        public int SysRatingId { get; set; }
        public int? Stars { get; set; }
    }
}