// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models.Entitites
{
    public partial class Trip
    {
        public int TripId { get; set; }
        public int CarId { get; set; }
        public int PaymentId { get; set; }
        public int LocationsId { get; set; }
        public DateTime CreationDate { get; set; }
        public int? SysRatingId { get; set; }

        public virtual Car Car { get; set; }
        public virtual Payment Payment { get; set; }
    }
}