// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReFeelRepository.Models
{
    public partial class ZipCode
    {
        public ZipCode()
        {
            County = new HashSet<County>();
        }

        public int ZipCodeId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<County> County { get; set; }
    }
}