-- use database
USE [Refeel];
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DriverRating' AND TABLE_SCHEMA = 'dbo')
BEGIN
   DROP TABLE [dbo].[DriverRating];
END
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DriverRating](
	[DriverRatingID] [int] IDENTITY(1,1) NOT NULL,
	[Average] int
 CONSTRAINT [PK_DriverRating] PRIMARY KEY CLUSTERED 
(
	[DriverRatingID] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

) 


GO


